
data:
  images_dir: "data/local/images/train"
  labels_dir: "annotations/labels/train"
  chan: 0
  chan2: 0
model:
  pretrained: "cyto3"
train:
  epochs: 100
  lr: 0.2
  batch_size: 8
  augment: true
